### ISSUE TITLE
Group 2 Phase 2 Water tiles everywhere

### ISSUE THREAD

**Issue by theshecoder** [cs340tabyu/CatanBugTracker#95] opened 2015-10-28 18:04 UTC
The Catan map populates with water tiles everywhere rather than just the border of the game map.

**Comment by matt-hoiland** [comment] 2015-10-30 18:08
I disagree that this is a bug.  I intentionally filled the board with water because I thought it looked cool. Also, this is a potential duplicate of #96. I will talk to the TAs about whether this needs to change.

**Closed as completed** 2015-11-09 18:26 UTC
Labels: Phase 2, Team 2, Fixing
