### ISSUE TITLE
Team 5 Phase 2

### ISSUE THREAD

**Issue by mwalker9** [cs340tabyu/CatanBugTracker#12] opened 2015-10-28 00:58 UTC
Steps:
Have only 2 victory points
Buy development card (Monument)
Next turn, open up development cards: click on monument, click to play card.

Result:
Card is played, raising victory points to 3

Expected result:
Card cannot be played because it does not give me enough victory points to win.

**Comment by tkwilli94** [comment] 2015-10-31 19:41
Our client works exactly the same as the demo client as far as Monument cards are concerned. We are marking this as not a bug.

**Closed as completed** 2015-11-09 18:37 UTC
Labels: Phase 2, Fixing
