### ISSUE TITLE
Group 2 phase 2 - Clients way out of sync

### ISSUE THREAD

**Issue by cache117** [cs340tabyu/CatanBugTracker#98] opened 2015-10-28 18:08 UTC
![image](https://cloud.githubusercontent.com/assets/11652513/10798278/882a9c80-7d6c-11e5-96e7-ce82abda9680.png)

Sorry, my clients were ordered in my screen improperly when I screenshotted this.

**Comment by matt-hoiland** [comment] 2015-10-30 17:59
@cache117 Is this a potential duplicate of #108? Please verify.

**Closed as completed** 2015-11-09 18:26 UTC
Labels: Phase 2, Team 2, Duplicate
