### ISSUE TITLE
Group 2 phase 2 - Map Doesn't load for 3 seconds. Too much water!

### ISSUE THREAD

**Issue by cache117** [cs340tabyu/CatanBugTracker#96] opened 2015-10-28 18:06 UTC
![image](https://cloud.githubusercontent.com/assets/11652513/10798220/395068c4-7d6c-11e5-8269-792e82a7c25d.png)
![image](https://cloud.githubusercontent.com/assets/11652513/10798223/3cebc848-7d6c-11e5-9640-bef6fc3f9661.png)

**Comment by matt-hoiland** [comment] 2015-10-30 18:10
Potential duplicate of #95. If these really are separate, then I agree that the loading of the map should be optimized.

**Closed as completed** 2015-11-09 18:26 UTC
Labels: Phase 2, Team 2, Duplicate
